version: "3"
services:
  db:
    container: flask_test_app_db_1
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - testing-volume:/var/lib/mysql

volumes:
  testing-volume: